---
- name: Update index
  hosts: all
  become: true

  tasks:
  - name: Delete old index
    file:
      path: /usr/share/nginx/html/index.html
      state: absent
      
  - name: Create and update content
    copy:
      dest: /usr/share/nginx/html/index.html
      content: |
        testy
