---
- name: Update index
  hosts: all
  become: true

  tasks:
  - name: delete old index
    file:
      path: /usr/share/nginx/html/index.html
      state: absent
      
  - name: Create an empty file
    file:
      path: /usr/share/nginx/html/index.html
      state: touch
      
  - name: update content
    blockinfile:
      path: /usr/share/nginx/html/index.html
      block: |
        testy
    state: present
